all:
	g++ -std=gnu++20 -Og -Wall -o listener listener.cpp
	g++ -std=gnu++20 -Og -Wall -o talker talker.cpp
	g++ -std=gnu++20 -Og -Wall -o nonblocking nonblocking.cpp

clean:
	rm ./listener
	rm ./talker
	rm ./nonblocking
