# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mygrpc/v1/greeter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mygrpc/v1/greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17mygrpc/v1/greeter.proto\x12\tmygrpc.v1\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cHelloReponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8e\x01\n\x07Greeter\x12>\n\x08SayHello\x12\x17.mygrpc.v1.HelloRequest\x1a\x17.mygrpc.v1.HelloReponse\"\x00\x12\x43\n\rSayHelloAgain\x12\x17.mygrpc.v1.HelloRequest\x1a\x17.mygrpc.v1.HelloReponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mygrpc.v1.greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=38
  _globals['_HELLOREQUEST']._serialized_end=66
  _globals['_HELLOREPONSE']._serialized_start=68
  _globals['_HELLOREPONSE']._serialized_end=99
  _globals['_GREETER']._serialized_start=102
  _globals['_GREETER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
