[package]
name = "zmq_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
hdf5 = "0.8.1"
hdf5-sys = { version = "0.8.1", features = ["static"] }
zmq = "0.10.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
